window.MS_CONFIG = {

  EVENT_NAME: "נופש החברה 2026",
LOGO_URL: "LOGO.jpg",
  
  ADMIN_PIN: "2026",
  WARMUP_QUESTION: "מי התלבש יותר יפה הערב?",
  WARMUP_OPTIONS: [
    {n:1, label:"ריבה"},
    {n:2, label:"עמוס"},
    {n:3, label:"שניהם מהממים"}
  ],
  SONGS: [
    {id:1, name:"אלף", bg:"#3a2410", stroke:"#f0c896",
      path:'<circle cx="20" cy="20" r="10"/><path d="M14 11 L11 5 M26 11 L29 5"/><ellipse cx="20" cy="24" rx="5" ry="4"/>',
      candidates: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],revealAnswer: 15,  costumePhoto: "song1.png"},
    {id:2, name:"החיפושית", bg:"#173a1c", stroke:"#a8e6ae",
      path:'<circle cx="20" cy="24" r="10"/><path d="M20 14 L20 34"/><circle cx="20" cy="11" r="4"/>',
      candidates: [21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40],revealAnswer: 26,  costumePhoto: "song2.png"},
    {id:3, name:"האריה", bg:"#5a3c14", stroke:"#f0c675",
      path:'<circle cx="20" cy="22" r="7"/><path d="M20 8 L23 14 M20 8 L17 14"/>',
      candidates: [41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60],revealAnswer: 59,  costumePhoto: "song3.png"},
    {id:4, name:"הפיל", bg:"#2c2c3a", stroke:"#dcdcf0",
      path:'<circle cx="19" cy="18" r="9"/><circle cx="8" cy="15" r="7"/>',
      candidates: [61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80],revealAnswer: 71,  costumePhoto: "song4.png"},
    {id:5, name:"הפנדה", bg:"#1c1c1c", stroke:"#ffffff",
      path:'<circle cx="20" cy="20" r="9"/><circle cx="9" cy="10" r="5"/><circle cx="31" cy="10" r="5"/>',
      candidates: [81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100],revealAnswer: 95,  costumePhoto: "song5.png"},
    {id:6, name:"התרנגול", bg:"#4a1414", stroke:"#f5b0a0",
      path:'<ellipse cx="17" cy="25" rx="9" ry="7"/><circle cx="26" cy="15" r="6"/>',
      candidates: [101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120],revealAnswer: 110, costumePhoto: "song6.png"}
  ],

  CANDIDATES: [
    {n:1,  name:"מיכאל פליישמן",  photo:"1.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:2,  name:"דניאל פריינטה",  photo:"2.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:3,  name:"אחמד זידאן",  photo:"3.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:4,  name:"תאאר טאהא",  photo:"4.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:5,  name:"זאיד כעביה",  photo:"5.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:6,  name:"חיים ברוך",  photo:"6.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:7,  name:"פואד חטיב",  photo:"7.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:8,  name:"אמיר גלטשטיין",  photo:"8.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:9,  name:"אלברטו בן בונאן",  photo:"9.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:10,  name:"מתן טל",  photo:"10.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:11,  name:"עומר ריאן",  photo:"11.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:12,  name:"אולג אוסטורוחוב",  photo:"12.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:13,  name:"ערן שוורצמן",  photo:"13.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:14,  name:"איתי ליכט",  photo:"14.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:15,  name:"אורן טהר לב",  photo:"15.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:16,  name:"עמוס אשכנזי",  photo:"16.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:17,  name:"מאור חולו",  photo:"17.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:18,  name:"איתמר סלוק",  photo:"18.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:19,  name:"עמית זית",  photo:"19.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:20,  name:"נחשון שטייף",  photo:"20.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:21,  name:"רותם צורף",  photo:"21.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:22,  name:"עדי שני",  photo:"22.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:23,  name:"זיוה טובול",  photo:"23.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:24,  name:"לינט חורש",  photo:"24.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:25,  name:"ליה חביב",  photo:"25.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:26,  name:"רונית שמאי",  photo:"26.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:27,  name:"קרן רייש",  photo:"27.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:28,  name:"שרונה אומרדקר",  photo:"28.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:29,  name:"חגית ענבר",  photo:"29.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:30,  name:"ענבר גולן ייני",  photo:"30.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:31,  name:"סנדרה גלנט",  photo:"31.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:32,  name:"אורה סוקולצקי",  photo:"32.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:33,  name:"סיגל חן",  photo:"33.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:34,  name:"פטל שחר",  photo:"34.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:35,  name:"גלית ארצי",  photo:"35.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:36,  name:"יעל אנקורי",  photo:"36.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:37,  name:"הלן מוסא",  photo:"37.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:38,  name:"סיגל לנצט",  photo:"38.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:39,  name:"גלית שושן",  photo:"39.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:40,  name:"אדוה פלג",  photo:"40.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:41,  name:"רפי כהן",  photo:"41.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:42,  name:"אחמד המאם",  photo:"42.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:43,  name:"ברק רמתי",  photo:"43.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:44,  name:"ענר בראב",  photo:"44.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:45,  name:"אלכס אומנסקי",  photo:"45.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:46,  name:"נחשון שטייף",  photo:"46.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:47,  name:"אמיר גלטשטיין",  photo:"47.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:48,  name:"חיים ברוך",  photo:"48.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:49,  name:"דניאל פריינטה",  photo:"49.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:50,  name:"זאב גולדנברג",  photo:"50.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:51,  name:"ולאד אוסטרובסקי",  photo:"51.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:52,  name:"עידן גולדשטיין",  photo:"52.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:53,  name:"ישראל ליבוביץ",  photo:"53.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:54,  name:"קמיליו מאז",  photo:"54.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:55,  name:"אמיר סלייפר",  photo:"55.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:56,  name:"אורי אפרת",  photo:"56.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:57,  name:"גיא סנדלר",  photo:"57.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:58,  name:"אבישי זמיר",  photo:"58.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:59,  name:"חנן פרחי",  photo:"59.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:60,  name:"ניצן ברדר",  photo:"60.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:61,  name:"חאלד חיג'אזי",  photo:"61.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:62,  name:"שאדי אבו עטא",  photo:"62.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:63,  name:"סובחי חאלדי",  photo:"63.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:64,  name:"מוחמד אבו אל היג'א",  photo:"64.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:65,  name:"מוסטפא המאם",  photo:"65.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:66,  name:"עומר סובח",  photo:"66.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:67,  name:"אחמד זידאן",  photo:"67.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:68,  name:"חאתם טהא",  photo:"68.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:69,  name:"חוסין בשיר",  photo:"69.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:70,  name:"עבד נמראנה",  photo:"70.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:71,  name:"הלאל אבו ניל",  photo:"71.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:72,  name:"נפאע נפאע",  photo:"72.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:73,  name:"זאיד כעביה",  photo:"73.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:74,  name:"מוהיב נעמה",  photo:"74.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:75,  name:"מאהר מג'דוב",  photo:"75.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:76,  name:"רמי דיאב",  photo:"76.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:77,  name:"באסל חאלדי",  photo:"77.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:78,  name:"חמזה זובידאת",  photo:"78.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:79,  name:"מוחמד חיג'אזי",  photo:"79.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:80,  name:"פאיז זובידאת",  photo:"80.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:81,  name:"סיגל חן",  photo:"81.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:82,  name:"יפעת קפלן",  photo:"82.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:83,  name:"שיר עמר",  photo:"83.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:84,  name:"טליה אפרת",  photo:"84.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:85,  name:"אורלי רום",  photo:"85.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:86,  name:"רוני דרור",  photo:"86.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:87,  name:"ליליה אייזנברג",  photo:"87.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:88,  name:"צביה חמאוואי",  photo:"88.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:89,  name:"ליהי דותן",  photo:"89.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:90,  name:"לימור ענתבי",  photo:"90.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:91,  name:"מירי פנחס",  photo:"91.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:92,  name:"מירב כרמון",  photo:"92.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:93,  name:"מירב הררי",  photo:"93.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:94,  name:"ליאור טולדנו",  photo:"94.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:95,  name:"שרון גולן",  photo:"95.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:96,  name:"טובה כדורי",  photo:"96.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:97,  name:"אופיר שביט",  photo:"97.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:98,  name:"עדי עוזרי",  photo:"98.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:99,  name:"יפעת ליכט",  photo:"99.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:100,  name:"בר ארד פשטי",  photo:"100.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:101,  name:"אחמד המאם",  photo:"101.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:102,  name:"אלי אסולין",  photo:"102.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:103,  name:"פואד חטיב",  photo:"103.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:104,  name:"ישראל ליבוביץ",  photo:"104.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:105,  name:"גיא סנדלר",  photo:"105.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:106,  name:"נועם קמרי",  photo:"106.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:107,  name:"ערן גולדמן",  photo:"107.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:108,  name:"תאאר טאהא",  photo:"108.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:109,  name:"זאב גולדנברג",  photo:"109.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:110,  name:"אדם בוחבוט",  photo:"110.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:111,  name:"רפי כהן",  photo:"111.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:112,  name:"מאור חולו",  photo:"112.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:113,  name:"שמעון סאינה",  photo:"113.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:114,  name:"סיסאי מינייב",  photo:"114.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:115,  name:"עידן גולדשטיין",  photo:"115.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:116,  name:"אמיר סלייפר",  photo:"116.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:117,  name:"מתן טל",  photo:"117.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:118,  name:"ולאד אוסטרובסקי",  photo:"118.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:119,  name:"איתי ליכט",  photo:"119.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false},
    {n:120,  name:"ניצן ברדר",  photo:"120.jpg", skin:"#e0ac69", hair_color:"#2c2c2c", hair_style:"buzz", facial_hair:"none", glasses:false}
  ],

  /* ⚠️ שימו לב: הערכים כאן למטה הם עדיין ה-דוגמה הכללית מה-README,
     ולא הערכים האמיתיים שלכם! צריך להיכנס לקונסולת Firebase →
     הגדרות הפרויקט (⚙️) → General → "Your apps" → אפליקציית ה-Web
     שלכם → ולהעתיק משם את שש השורות האמיתיות של firebaseConfig,
     ולהדביק אותן במקום השורות הבאות: */
  FIREBASE_CONFIG: {
    apiKey: "AIza...",
    authDomain: "masked-singer-palram.firebaseapp.com",
    projectId: "masked-singer-palram",
    storageBucket: "masked-singer-palram.appspot.com",
    messagingSenderId: "123456789",
    appId: "1:123456789:web:abcdef123456"
  }
};
